# -*- coding: utf-8 -*-
"""SIMULADOR-DIVIDENDOS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOw1xvQWySsSPASTY1jB6SztIjk5qQDP
"""

# -*- coding: utf-8 -*-
# Simulador IRRF 10% + IRPFM 0–10% — PL 1.087/2025 (UI fixa + resumo robusto)
# - Accordion abre por padrão (selected_index=0)
# - Widgets sempre visíveis (UI num único VBox)
# - Resumo em HTML (sem pipes) para evitar quebras
# - Mesmo motor auditado (IRRF 10%, IRPFM 0–10% com abatimentos, redutor 16-B aprox.)

try:
    from google.colab import output  # type: ignore
    output.enable_custom_widget_manager()
except Exception:
    pass

import re, datetime as dt
import pandas as pd
import numpy as np
import ipywidgets as w
from IPython.display import display, HTML, Markdown
import traceback
import logging

pd.options.display.float_format = lambda v: f"{v:,.2f}".replace(",", "X").replace(".", ",").replace("X",".")

# --- Configuração do sistema de log ---
def setup_logging():
    """Configura o sistema de logging para erros"""
    logging.basicConfig(
        level=logging.ERROR,
        format='%(asctime)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler('erro_simulador.log', encoding='utf-8'),
            logging.StreamHandler()
        ]
    )
    return logging.getLogger(__name__)

logger = setup_logging()

def log_error(error_msg, exception=None):
    """Registra erro no log e exibe para o usuário"""
    timestamp = dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    error_details = f"[{timestamp}] ERRO: {error_msg}"

    if exception:
        error_details += f"\nExceção: {str(exception)}"
        error_details += f"\nTraceback: {traceback.format_exc()}"

    logger.error(error_details)

    # Exibe erro para o usuário
    with out_main:
        out_main.clear_output()
        display(HTML(f"""
            <div style="background:#fee2e2;border:2px solid #ef4444;border-radius:8px;padding:15px;margin:10px 0;">
                <h3 style="margin:0;color:#991b1b;">❌ Erro no Sistema</h3>
                <p style="margin:5px 0;color:#991b1b;"><strong>Mensagem:</strong> {error_msg}</p>
                <p style="margin:5px 0;color:#991b1b;"><strong>Log:</strong> Verifique o arquivo 'erro_simulador.log'</p>
            </div>
        """))

# --- Mapeamento de alíquotas por regime PJ ---
ALIQUOTAS_REGIME_PJ = {
    "Simples Nacional": 8.0,
    "Lucro Presumido": 15.0,
    "Lucro Real": 34.0
}

APP_TITLE = "Simulador IRRF 10% + IRPFM 0–10% — PL 1.087/2025"
APP_SUB   = ("Preencha os dados, ajuste os parâmetros e clique em <b>RODAR SIMULAÇÃO</b>. "
             "Simulação educacional; pontos como o redutor 16-B são aproximados.")

def fmt_brl(v):
    try: s = float(v)
    except Exception: return "R$ 0,00"
    neg = s < 0; s = abs(s)
    s_str = f"{s:,.2f}".replace(",", "X").replace(".", ",").replace("X",".")
    return f"- R$ {s_str}" if neg else f"R$ {s_str}"

def parse_brl(s):
    if s is None: return 0.0
    if isinstance(s, (int,float)): return float(s)
    s = re.sub(r"[^\d,.-]", "", str(s))
    if "," in s and "." in s: s = s.replace(".","").replace(",",".")
    elif "," in s:            s = s.replace(",",".")
    try: return float(s)
    except Exception: return 0.0

def format_brl_live(value):
    """Formata valor monetário em tempo real conforme o usuário digita"""
    if not value or value == "":
        return ""

    # Remove tudo exceto números
    clean_value = re.sub(r"[^\d]", "", str(value))

    # Se não tem números, retorna vazio
    if not clean_value:
        return ""

    # Remove zeros à esquerda, mas mantém pelo menos um zero
    clean_value = clean_value.lstrip('0') or '0'

    # Se tem apenas 1 dígito, retorna como centavos
    if len(clean_value) == 1:
        return f"0,0{clean_value}"

    # Se tem 2 dígitos, retorna como centavos
    if len(clean_value) == 2:
        return f"0,{clean_value}"

    # Se tem mais de 2 dígitos, formata com separadores de milhares
    # Separa a parte decimal (2 últimos dígitos) da parte inteira
    parte_inteira = clean_value[:-2]
    parte_decimal = clean_value[-2:]

    # Formata a parte inteira com pontos como separadores de milhares
    if len(parte_inteira) > 3:
        # Formatação mais simples: adiciona pontos a cada 3 dígitos
        parte_inteira_formatada = ""
        for i, digit in enumerate(parte_inteira):
            if i > 0 and (len(parte_inteira) - i) % 3 == 0:
                parte_inteira_formatada += "."
            parte_inteira_formatada += digit
    else:
        parte_inteira_formatada = parte_inteira

    return f"{parte_inteira_formatada},{parte_decimal}"

def on_brl_change(change, widget):
    """Callback para formatação em tempo real"""
    try:
        if change['new'] is not None:
            new_value = str(change['new'])
            old_value = str(change.get('old', ''))

            # Se o usuário está digitando (não é uma mudança programática)
            if new_value != old_value:
                # Se o campo está vazio, não faz nada
                if not new_value:
                    return

                # Se já está formatado com R$, não interfere
                if new_value.startswith("R$"):
                    return

                # Se o usuário digitou apenas números, formata em tempo real
                if re.match(r'^[\d,\.]*$', new_value):
                    formatted = format_brl_live(new_value)
                    if formatted and formatted != new_value:
                        # Atualiza sem triggerar o callback novamente
                        widget.unobserve_all()
                        widget.value = formatted
                        widget.observe(lambda change: on_brl_change(change, widget), names='value')

                # Se o usuário digitou algo que parece um valor monetário sem R$
                elif "," in new_value and not new_value.startswith("R$"):
                    # Adiciona R$ se não tem
                    if not new_value.startswith("R$"):
                        widget.unobserve_all()
                        widget.value = f"R$ {new_value}"
                        widget.observe(lambda change: on_brl_change(change, widget), names='value')
    except Exception as e:
        # Em caso de erro, mantém o valor original
        pass


# --- Tabelas Oficiais da Receita Federal (2025) ---

# M1 — Tabela progressiva mensal (IRRF) vigente "a partir de maio/2025"
TABELA_M1 = [
    {"faixa_min": 0, "faixa_max": 2428.80, "aliquota": 0.0, "parcela_deduzir": 0.0},
    {"faixa_min": 2428.81, "faixa_max": 2826.65, "aliquota": 0.075, "parcela_deduzir": 182.16},
    {"faixa_min": 2826.66, "faixa_max": 3751.05, "aliquota": 0.15, "parcela_deduzir": 394.16},
    {"faixa_min": 3751.06, "faixa_max": 4664.68, "aliquota": 0.225, "parcela_deduzir": 675.49},
    {"faixa_min": 4664.69, "faixa_max": float('inf'), "aliquota": 0.275, "parcela_deduzir": 908.73}
]

# Tabela progressiva ANUAL (para ajuste anual IRPF)
TABELA_ANUAL_IRPF = [
    {"faixa_min": 0, "faixa_max": 29145.60, "aliquota": 0.0, "parcela_deduzir": 0.0},
    {"faixa_min": 29145.61, "faixa_max": 33919.80, "aliquota": 0.075, "parcela_deduzir": 2185.92},
    {"faixa_min": 33919.81, "faixa_max": 45012.60, "aliquota": 0.15, "parcela_deduzir": 4729.92},
    {"faixa_min": 45012.61, "faixa_max": 55976.16, "aliquota": 0.225, "parcela_deduzir": 8105.88},
    {"faixa_min": 55976.17, "faixa_max": float('inf'), "aliquota": 0.275, "parcela_deduzir": 10904.76}
]

# M2 — Tabela exclusiva do PLR "a partir de maio/2025"
TABELA_M2 = [
    {"faixa_min": 0, "faixa_max": 8214.40, "aliquota": 0.0, "parcela_deduzir": 0.0},
    {"faixa_min": 8214.41, "faixa_max": 9922.28, "aliquota": 0.075, "parcela_deduzir": 616.08},
    {"faixa_min": 9922.29, "faixa_max": 13167.00, "aliquota": 0.15, "parcela_deduzir": 1360.25},
    {"faixa_min": 13167.01, "faixa_max": 16380.38, "aliquota": 0.225, "parcela_deduzir": 2347.78},
    {"faixa_min": 16380.39, "faixa_max": float('inf'), "aliquota": 0.275, "parcela_deduzir": 3166.80}
]

# M3 — Regressiva (renda fixa e fundos de longo prazo)
TABELA_M3 = {
    "curto_prazo": {"ate_180_dias": 0.225, "acima_180_dias": 0.20},
    "longo_prazo": {"ate_180_dias": 0.225, "181_360_dias": 0.20, "361_720_dias": 0.175, "acima_720_dias": 0.15}
}

# M4 — Ganho de capital fora de bolsa (faixas 15–22,5%)
TABELA_M4 = [
    {"faixa_min": 0, "faixa_max": 5000000.00, "aliquota": 0.15},
    {"faixa_min": 5000000.01, "faixa_max": 10000000.00, "aliquota": 0.175},
    {"faixa_min": 10000000.01, "faixa_max": 30000000.00, "aliquota": 0.20},
    {"faixa_min": 30000000.01, "faixa_max": float('inf'), "aliquota": 0.225}
]

def calcular_irrf_tabela_m1(valor_mensal):
    """Calcula IRRF usando tabela M1 (progressiva mensal)"""
    for faixa in TABELA_M1:
        if faixa["faixa_min"] <= valor_mensal <= faixa["faixa_max"]:
            return valor_mensal * faixa["aliquota"] - faixa["parcela_deduzir"]
    return 0.0

def calcular_irrf_tabela_m2(valor_anual):
    """Calcula IRRF usando tabela M2 (PLR)"""
    for faixa in TABELA_M2:
        if faixa["faixa_min"] <= valor_anual <= faixa["faixa_max"]:
            return valor_anual * faixa["aliquota"] - faixa["parcela_deduzir"]
    return 0.0

def calcular_irrf_tabela_m3(valor, prazo_dias, tipo="longo_prazo"):
    """Calcula IRRF usando tabela M3 (regressiva por prazo)"""
    if tipo == "curto_prazo":
        if prazo_dias <= 180:
            return valor * TABELA_M3["curto_prazo"]["ate_180_dias"]
        else:
            return valor * TABELA_M3["curto_prazo"]["acima_180_dias"]
    else:  # longo_prazo
        if prazo_dias <= 180:
            return valor * TABELA_M3["longo_prazo"]["ate_180_dias"]
        elif prazo_dias <= 360:
            return valor * TABELA_M3["longo_prazo"]["181_360_dias"]
        elif prazo_dias <= 720:
            return valor * TABELA_M3["longo_prazo"]["361_720_dias"]
        else:
            return valor * TABELA_M3["longo_prazo"]["acima_720_dias"]

def calcular_irrf_tabela_m4(valor_ganho):
    """Calcula IRRF usando tabela M4 (ganho de capital)"""
    for faixa in TABELA_M4:
        if faixa["faixa_min"] <= valor_ganho <= faixa["faixa_max"]:
            return valor_ganho * faixa["aliquota"]
    return 0.0

def calcular_ir_exclusivo_automatico(tipo_renda, valor_anual, prazo_dias=None):
    """Calcula IR exclusivo automaticamente baseado no tipo de renda e tabelas oficiais"""
    if tipo_renda not in TIPOS_RENDA:
        return 0.0

    config = TIPOS_RENDA[tipo_renda]
    tabela_id = config["tabela_id"]

    # Se tem IR exclusivo fixo, usa a porcentagem
    if config["ir_exclusivo_pct"] > 0:
        return valor_anual * (config["ir_exclusivo_pct"] / 100)

    # Se usa tabelas progressivas/regressivas
    if tabela_id == "M1":
        # Para tabela M1, assume valor mensal (divide por 12)
        valor_mensal = valor_anual / 12
        return calcular_irrf_tabela_m1(valor_mensal) * 12

    elif tabela_id == "M2":
        # Para PLR, usa valor anual direto
        return calcular_irrf_tabela_m2(valor_anual)

    elif tabela_id == "M3":
        # Para renda fixa, precisa do prazo
        if prazo_dias is None:
            prazo_dias = 365  # Assume 1 ano se não informado
        return calcular_irrf_tabela_m3(valor_anual, prazo_dias)

    elif tabela_id == "M4":
        # Para ganho de capital
        return calcular_irrf_tabela_m4(valor_anual)

    # Para isentos ou outros casos
    return 0.0

def calcular_irpf_anual(base_anual):
    """Calcula IRPF usando tabela progressiva anual"""
    for faixa in TABELA_ANUAL_IRPF:
        if faixa["faixa_min"] <= base_anual <= faixa["faixa_max"]:
            return base_anual * faixa["aliquota"] - faixa["parcela_deduzir"]
    return 0.0

def calcular_reducao_art11A(base_anual):
    """Calcula redução do art. 11-A para rendas até 84k (PL 1.087/2025)"""
    # Simplificação: se base <= 84.000, aplica redução
    # Para implementação completa, usar a fórmula exata da lei
    if base_anual <= 84000:
        return base_anual * 0.05  # 5% de redução (simplificado)
    return 0.0

def apurar_irpf_normal_anual(df_rends, deducoes=0):
    """
    Apura IRPF "normal" do ajuste anual
    Retorna: (ir_devido_anual, irrf_normal, saldo_irpf_normal)
    """
    # Soma rendas tributáveis no ajuste (tribut avel_ajuste == 1)
    base_ajuste = 0.0
    irrf_normal = 0.0

    for _, renda in df_rends.iterrows():
        tipo = renda.get("tipo", "")
        valor = renda.get("valor_anual", 0.0)

        if tipo in TIPOS_RENDA:
            config = TIPOS_RENDA[tipo]
            # Se é tributável no ajuste
            if config["tributavel_ajuste"] == 1:
                base_ajuste += valor

            # IRRF normal (M1 progressivo mensal)
            if config["tabela_id"] == "M1" and config["tributavel_ajuste"] == 1:
                valor_mensal = valor / 12
                irrf_normal += calcular_irrf_tabela_m1(valor_mensal) * 12

    # Aplica deduções
    base_ajuste = max(0, base_ajuste - deducoes)

    # Calcula IR devido anual
    ir_devido_anual = calcular_irpf_anual(base_ajuste)

    # Aplica redução do art. 11-A
    reducao_11a = calcular_reducao_art11A(base_ajuste)
    ir_devido_anual = max(0, ir_devido_anual - reducao_11a)

    # Saldo IRPF normal
    saldo_irpf_normal = ir_devido_anual - irrf_normal

    return ir_devido_anual, irrf_normal, saldo_irpf_normal

def apurar_base_irpfm(df_rends, df_divs):
    """
    Apura base do IRPFM (REND - exceções do §3)
    Exceções: poupança, indenizações, FIIs/Fiagros, LCI/LCA/CRI/CRA isentos
    """
    rend_total = 0.0

    # Soma rendas que contam para REND (conta_REND == 1)
    for _, renda in df_rends.iterrows():
        tipo = renda.get("tipo", "")
        valor = renda.get("valor_anual", 0.0)

        if tipo in TIPOS_RENDA:
            config = TIPOS_RENDA[tipo]
            if config["conta_REND"] == 1:
                rend_total += valor

    # Soma dividendos (sempre contam para REND)
    total_dividendos = df_divs["valor"].sum() if not df_divs.empty else 0.0
    rend_total += total_dividendos

    # Aplica exceções do §3 (base IRPFM)
    base_irpfm = rend_total

    # Remove rendas que não incluem na base (inclui_BASE == 0)
    for _, renda in df_rends.iterrows():
        tipo = renda.get("tipo", "")
        valor = renda.get("valor_anual", 0.0)

        if tipo in TIPOS_RENDA:
            config = TIPOS_RENDA[tipo]
            if config["conta_REND"] == 1 and config["inclui_BASE"] == 0:
                base_irpfm -= valor

    return rend_total, max(0, base_irpfm)

def calcular_aliquota_irpfm(rend_base):
    """
    Calcula alíquota IRPFM (0% a 10%) conforme art. 16-A
    REND ≤ 600.000 → 0%
    600.000 < REND < 1.200.000 → linear
    REND ≥ 1.200.000 → 10%
    """
    if rend_base <= 600000:
        return 0.0
    elif rend_base >= 1200000:
        return 0.10
    else:
        # Linear entre 600k e 1.2M
        return 0.10 * ((rend_base - 600000) / 600000)

def apurar_irpfm(df_rends, df_divs, df_pj, ir_devido_anual, deducoes_extras=0):
    """
    Apura IRPFM (Imposto de Renda Mínimo)
    Retorna: (irpfm_bruto, irpfm_liquido, irpfm_antecipado, saldo_irpfm)
    """
    # Calcula base IRPFM
    rend_total, base_irpfm = apurar_base_irpfm(df_rends, df_divs)

    # Calcula alíquota IRPFM
    aliq_irpfm = calcular_aliquota_irpfm(base_irpfm)

    # IRPFM bruto
    irpfm_bruto = aliq_irpfm * base_irpfm

    # Deduções do §4 do art. 16-A
    deducoes_irpfm = ir_devido_anual

    # (ii) IR exclusivo retido na fonte sobre rendas incluídas na base do IRPFM
    ir_exclusivo_retido = 0.0
    for _, renda in df_rends.iterrows():
        tipo = renda.get("tipo", "")
        ir_exclusivo = renda.get("irrf_exclusivo_fonte", 0.0)

        if tipo in TIPOS_RENDA:
            config = TIPOS_RENDA[tipo]
            if config["inclui_BASE"] == 1:
                ir_exclusivo_retido += ir_exclusivo

    deducoes_irpfm += ir_exclusivo_retido

    # (v) Redutor 16-B (simplificado - pode ser expandido)
    redutor_16b = 0.0
    # TODO: Implementar cálculo completo do redutor 16-B

    deducoes_irpfm += redutor_16b + deducoes_extras

    # IRPFM líquido
    irpfm_liquido = max(0, irpfm_bruto - deducoes_irpfm)

    # IRPFM antecipado (IRRF 10% sobre dividendos)
    irpfm_antecipado = 0.0
    if not df_divs.empty and "irrf_10" in df_divs.columns:
        irpfm_antecipado = df_divs["irrf_10"].sum()

    # Saldo IRPFM
    saldo_irpfm = irpfm_liquido - irpfm_antecipado

    return irpfm_bruto, irpfm_liquido, irpfm_antecipado, saldo_irpfm, aliq_irpfm, base_irpfm, rend_total

def conciliar_final_art13(saldo_irpf_normal, saldo_irpfm):
    """
    Conciliação final (Art. 13): pagar vs. restituir
    Se negativo → restituição
    Se positivo → imposto a pagar
    """
    saldo_final = saldo_irpf_normal + saldo_irpfm

    if saldo_final < 0:
        return "restituir", abs(saldo_final), 0.0
    else:
        return "pagar", 0.0, saldo_final

# --- Configuração de tipos de renda com tabelas oficiais ---
TIPOS_RENDA = {
    # 1) Trabalho e serviços
    "Salário CLT": {
        "tabela_id": "M1", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Progressivo mensal (M1) - fonte 0561"
    },
    "Pró-labore (sócio)": {
        "tabela_id": "M1", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Progressivo mensal (M1) - fonte 0561"
    },
    "Autônomo / RPA": {
        "tabela_id": "M1", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Progressivo mensal (M1) - fonte 0588"
    },
    "Comissões/Honorários (PF)": {
        "tabela_id": "M1", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Progressivo mensal (M1) - fonte 0588"
    },
    "13º salário": {
        "tabela_id": "M1", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Exclusivo na fonte (M1) - fonte 0561-13"
    },
    "PLR": {
        "tabela_id": "M2", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Exclusivo na fonte (M2) - fonte 3562"
    },

    # 2) Capital e financeiros
    "JCP (Juros Capital Próprio)": {
        "tabela_id": "FIXO_15", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 15.0,
        "tributavel_ajuste": 0, "obs": "15% exclusivo na fonte - fonte 5706"
    },
    "CDB/Tesouro/Fundos LP": {
        "tabela_id": "M3", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 0, "obs": "Regressiva por prazo (M3) - instituição 6800"
    },
    "Fundos de Ações": {
        "tabela_id": "FIXO_15", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 15.0,
        "tributavel_ajuste": 0, "obs": "15% exclusivo na fonte - instituição"
    },
    "Ganho em Bolsa": {
        "tabela_id": "FIXO_15", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 15.0,
        "tributavel_ajuste": 0, "obs": "15% comum / 20% day-trade - autorrecolhimento 6015"
    },
    "FIIs/Fiagros": {
        "tabela_id": "ISENTO", "conta_REND": 1, "inclui_BASE": 0, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 0, "obs": "Isento (excluído da base)"
    },
    "LCI/LCA/CRI/CRA": {
        "tabela_id": "ISENTO", "conta_REND": 1, "inclui_BASE": 0, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 0, "obs": "Isento (excluído da base)"
    },
    "Cripto (Ganho de Capital)": {
        "tabela_id": "M4", "conta_REND": 0, "inclui_BASE": 0, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 0, "obs": "Progressivo por valor (M4) - autorrecolhimento 4600"
    },

    # 3) Patrimônio / propriedade
    "Aluguel via PJ": {
        "tabela_id": "M1", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Progressivo mensal (M1) - fonte 3208"
    },
    "Aluguel PF→PF (Carnê-Leão)": {
        "tabela_id": "M1", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Progressivo mensal (M1) - autorrecolhimento 0190"
    },
    "Arrendamento Rural": {
        "tabela_id": "M1", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Progressivo mensal (M1) - fonte 3208"
    },
    "Royalties/Direitos": {
        "tabela_id": "M1", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Progressivo mensal (M1) - fonte 3208"
    },
    "Ganho Capital (Imóvel/Bem)": {
        "tabela_id": "M4", "conta_REND": 0, "inclui_BASE": 0, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 0, "obs": "Progressivo por valor (M4) - autorrecolhimento 4600"
    },
    "Doações/Heranças": {
        "tabela_id": "ISENTO", "conta_REND": 0, "inclui_BASE": 0, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 0, "obs": "Isento no IR (ITCMD)"
    },

    # 4) Previdência e benefícios
    "Aposentadoria/Pensão": {
        "tabela_id": "M1", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Progressivo mensal (M1) - fonte 0561"
    },
    "PGBL/VGBL (Progressivo)": {
        "tabela_id": "M1", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Progressivo mensal (M1) - fonte 3223"
    },
    "PGBL/VGBL (Regressivo)": {
        "tabela_id": "REG_PREV", "conta_REND": 1, "inclui_BASE": 1, "ir_exclusivo_pct": 0.0,
        "tributavel_ajuste": 1, "obs": "Regressivo por tempo (10-35%) - Lei 11.053/2004"
    }
}
TETOS_SETORIAIS = {"Geral (34%)": 34.0, "Intermediário (40%)": 40.0, "Financeiro (45%)": 45.0}

# --- Estado ---
df_divs = pd.DataFrame(columns=[
    "data","cnpj_pagador","valor","fonte_simples_excecao","beneficiario_residente_brasil",
    "periodicidade","n_meses","regime_pj","valor_isento","valor_tributavel","irrf_10"
])
df_rends = pd.DataFrame(columns=["tipo","valor_anual","conta_para_REND","inclui_na_base","irrf_exclusivo_fonte","obs"])
df_pj    = pd.DataFrame(columns=["cnpj","aliquota_pj","teto_setorial"])

# --- Widgets: Parâmetros ---
p_piso   = w.Text(value="R$ 50.000,00", description="Piso mensal PF (R$):", layout=w.Layout(width="400px"))
p_irrf_f = w.FloatText(value=0.10, step=0.01, description="IRRF Div. (fração, ex.: 0,10):", layout=w.Layout(width="450px"))
p_r0     = w.Text(value="R$ 600.000,00", description="REND 0% até (R$):", layout=w.Layout(width="400px"))
p_r10    = w.Text(value="R$ 1.200.000,00", description="REND 10% a partir (R$):", layout=w.Layout(width="450px"))
p_use16b = w.Checkbox(value=True, description="Aplicar redutor art. 16-B (aprox.)")
p_simp_exc = w.Dropdown(options=["Não","Sim"], value="Não", description="Simples (Exceção)?", layout=w.Layout(width="300px"))

param_box = w.VBox([
    w.HTML('<div class="param-title">Parâmetros Legais / de Negócio</div>'),
    w.HBox([p_piso, p_irrf_f]),
    w.HBox([p_r0, p_r10]),
    w.HBox([p_use16b, p_simp_exc])
])

# --- Widgets: Dividendos ---
d_data = w.DatePicker(description="Data inicial", value=dt.date(2026,1,1), layout=w.Layout(width="350px"))
d_cnpj = w.Text(description="CNPJ", placeholder="00.000.000/0000-00", layout=w.Layout(width="400px"))
d_val  = w.Text(value="R$ 0,00", description="Valor (R$)", layout=w.Layout(width="350px"))
# Aplica formatação automática
d_val.observe(lambda change: on_brl_change(change, d_val), names='value')
d_per  = w.Dropdown(options=["Única (uma vez)","Mensal (linear)","Trimestral (linear)"], value="Única (uma vez)",
                    description="Periodicidade", layout=w.Layout(width="380px"))
d_n    = w.Dropdown(options=list(range(1, 13)), value=1, description="N meses", layout=w.Layout(width="250px"))

def _atualizar_n_meses(_=None):
    """Atualiza automaticamente o campo N meses baseado na periodicidade"""
    periodicidade = d_per.value

    if periodicidade == "Única (uma vez)":
        d_n.value = 1
        d_n.disabled = True
    elif periodicidade == "Mensal (linear)":
        d_n.disabled = False
        if d_n.value == 1:  # Se estava em 1 (única vez), ajusta para 12
            d_n.value = 12
    elif periodicidade == "Trimestral (linear)":
        d_n.value = 4  # 12/3 = 4
        d_n.disabled = True

# Conecta o callback ao dropdown de periodicidade
d_per.observe(_atualizar_n_meses, names="value")
d_res  = w.Dropdown(options=["Residente","Não residente"], value="Residente", description="Residência", layout=w.Layout(width="300px"))
d_reg  = w.Dropdown(options=["Lucro Real","Lucro Presumido","Simples Nacional"], value="Lucro Real",
                    description="Regime da PJ", layout=w.Layout(width="320px"))
btn_add_div = w.Button(description="Adicionar", button_style="success", icon="plus")
btn_rm_div  = w.Button(description="Remover última", button_style="warning", icon="trash")
out_divs    = w.Output()

def _atualizar_aliquota_pj(_=None):
    """Atualiza automaticamente a alíquota PJ baseada no regime selecionado"""
    try:
        regime_selecionado = d_reg.value
        if regime_selecionado in ALIQUOTAS_REGIME_PJ:
            nova_aliquota = ALIQUOTAS_REGIME_PJ[regime_selecionado]
            pj_aliq.value = nova_aliquota

            # Atualiza também o teto setorial se necessário
            if regime_selecionado == "Simples Nacional":
                pj_teto.value = "Geral (34%)"
            elif regime_selecionado == "Lucro Presumido":
                pj_teto.value = "Geral (34%)"
            else:  # Lucro Real
                pj_teto.value = "Geral (34%)"
    except Exception as e:
        log_error("Erro ao atualizar alíquota PJ automaticamente", e)

# Conecta o callback ao dropdown do regime PJ
d_reg.observe(_atualizar_aliquota_pj, names="value")

# Atualiza a alíquota inicial baseada no regime padrão
_atualizar_aliquota_pj()

def _add_div(_):
    global df_divs
    add = dict(
        data=d_data.value, cnpj_pagador=d_cnpj.value.strip(), valor=parse_brl(d_val.value),
        fonte_simples_excecao= 1 if p_simp_exc.value=="Sim" else 0,
        beneficiario_residente_brasil= 1 if d_res.value=="Residente" else 0,
        periodicidade=d_per.value, n_meses=int(d_n.value or 1), regime_pj=d_reg.value,
        valor_isento=0.0, valor_tributavel=0.0, irrf_10=0.0
    )
    new_row = pd.DataFrame([add])
    if df_divs.empty:
        df_divs = new_row.copy()
    else:
        df_divs = pd.concat([df_divs, new_row], ignore_index=True)
    _render_divs()
    _atualizar_cnpj_pj_options()  # Atualiza opções do CNPJ PJ

def _rm_div(_):
    global df_divs
    if not df_divs.empty: df_divs = df_divs.iloc[:-1].copy()
    _render_divs()
    _atualizar_cnpj_pj_options()  # Atualiza opções do CNPJ PJ

def _render_divs():
    with out_divs:
        out_divs.clear_output()
        if df_divs.empty:
            display(Markdown("_Sem dividendos cadastrados._"))
        else:
            tmp = df_divs.copy(); tmp["valor"] = tmp["valor"].map(fmt_brl)
            display(Markdown("**Dividendos cadastrados**"))
            display(tmp)

btn_add_div.on_click(_add_div); btn_rm_div.on_click(_rm_div)
div_box = w.VBox([
    w.HTML('<div class="param-title">Dividendos</div>'),
    w.HBox([d_data, d_cnpj, d_val]),
    w.HBox([d_per, d_n]),
    w.HBox([d_res, d_reg]),
    w.HBox([btn_add_div, btn_rm_div]),
    out_divs
])
_render_divs()

# --- Widgets: Saldo Isento 2025 ---
saldo_tem_lucro_nd = w.Checkbox(value=False, description="Existe lucro não distribuído apurado até 2025?", layout=w.Layout(width="450px"))
saldo_deliberado_2025 = w.Checkbox(value=False, description="Deliberação aprovada até 31/12/2025?", layout=w.Layout(width="450px"))
saldo_valor_aprovado = w.Text(value="R$ 0,00", description="Valor aprovado para distribuição (R$)", layout=w.Layout(width="450px"))
# Aplica formatação automática
saldo_valor_aprovado.observe(lambda change: on_brl_change(change, saldo_valor_aprovado), names='value')

saldo_box = w.VBox([
    w.HTML('<div class="param-title">Saldo Isento 2025 (Regra Simplificada)</div>'),
    w.HTML('<div class="hint">Base legal: lucros até 2025 deliberados até 31/12/2025 seguem isentos mesmo se pagos em 2026–2028.</div>'),
    saldo_tem_lucro_nd,
    saldo_deliberado_2025,
    saldo_valor_aprovado,
    w.HTML('<div class="hint">Este saldo pode ser usado para pagamentos de 01/01/2026 a 31/12/2028. Após esta data, o saldo expira.</div>')
])

# --- Widgets: Outras rendas ---
r_tipo = w.Dropdown(options=list(TIPOS_RENDA.keys()), value="Salário CLT", description="Tipo", layout=w.Layout(width="600px"))
r_val  = w.Text(value="R$ 0,00", description="Valor anual (R$)", layout=w.Layout(width="350px"))
r_ir   = w.Text(value="R$ 0,00", description="IR exclusivo (R$)", layout=w.Layout(width="350px"), disabled=True)
r_cont = w.Dropdown(options=["Sim","Não"], value="Sim", description="Conta p/ REND (§1)", layout=w.Layout(width="350px"), disabled=True)
r_base = w.Dropdown(options=["Sim","Não"], value="Sim", description="Inclui na Base (§3)", layout=w.Layout(width="350px"), disabled=True)

def _atualizar_campos_renda(_=None):
    """Atualiza automaticamente os campos de renda baseado no tipo selecionado"""
    try:
        tipo_selecionado = r_tipo.value
        if tipo_selecionado in TIPOS_RENDA:
            config = TIPOS_RENDA[tipo_selecionado]

            # Atualiza "Conta p/ REND (§1)"
            r_cont.value = "Sim" if config["conta_REND"] == 1 else "Não"

            # Atualiza "Inclui na Base (§3)"
            r_base.value = "Sim" if config["inclui_BASE"] == 1 else "Não"

            # Calcula IR exclusivo automaticamente
            valor_anual = parse_brl(r_val.value)
            ir_exclusivo = calcular_ir_exclusivo_automatico(tipo_selecionado, valor_anual)
            r_ir.value = fmt_brl(ir_exclusivo)

            # Atualiza observação
            r_obs.value = f"Tabela: {config['tabela_id']} | {config['obs']}"

    except Exception as e:
        log_error(e, "_atualizar_campos_renda")

def _atualizar_ir_exclusivo(_=None):
    """Recalcula IR exclusivo quando o valor muda"""
    try:
        tipo_selecionado = r_tipo.value
        if tipo_selecionado in TIPOS_RENDA:
            valor_anual = parse_brl(r_val.value)
            ir_exclusivo = calcular_ir_exclusivo_automatico(tipo_selecionado, valor_anual)
            r_ir.value = fmt_brl(ir_exclusivo)
    except Exception as e:
        log_error(e, "_atualizar_ir_exclusivo")

# Aplica formatação automática aos campos monetários
r_val.observe(lambda change: on_brl_change(change, r_val), names='value')
r_val.observe(lambda change: _atualizar_ir_exclusivo(), names='value')
r_ir.observe(lambda change: on_brl_change(change, r_ir), names='value')

# Atualiza campos quando tipo de renda muda
r_tipo.observe(lambda change: _atualizar_campos_renda(), names='value')
r_obs  = w.Label(value="")
btn_add_r = w.Button(description="Adicionar", button_style="success", icon="plus")
btn_rm_r  = w.Button(description="Remover última", button_style="warning", icon="trash")
out_r     = w.Output()

# Inicializa os campos automaticamente
_atualizar_campos_renda()

def _add_r(_):
    global df_rends
    try:
        info = TIPOS_RENDA.get(r_tipo.value, TIPOS_RENDA["Salário CLT"])
        add = dict(
            tipo=r_tipo.value, valor_anual=parse_brl(r_val.value),
            conta_para_REND=1 if info["conta_REND"] else 0,
            inclui_na_base=1 if info["inclui_BASE"] else 0,
            irrf_exclusivo_fonte=parse_brl(r_ir.value), obs=info["obs"]
        )
        new_row = pd.DataFrame([add])
        if df_rends.empty:
            df_rends = new_row.copy()
        else:
            df_rends = pd.concat([df_rends, new_row], ignore_index=True)
        _render_r()
    except Exception as e:
        log_error(e, "_add_r")

def _rm_r(_):
    global df_rends
    if not df_rends.empty: df_rends = df_rends.iloc[:-1].copy()
    _render_r()

def _render_r():
    with out_r:
        out_r.clear_output()
        if df_rends.empty:
            display(Markdown("_Sem outras rendas cadastradas._"))
        else:
            t = df_rends.copy()
            t["valor_anual"] = t["valor_anual"].map(fmt_brl)
            t["irrf_exclusivo_fonte"] = t["irrf_exclusivo_fonte"].map(fmt_brl)
            t = t.rename(columns={"conta_para_REND":"conta_REND(§1)","inclui_na_base":"inclui_BASE(§3)"})
            display(Markdown("**Outras rendas cadastradas**"))
            display(t)

btn_add_r.on_click(_add_r); btn_rm_r.on_click(_rm_r)
r_box = w.VBox([
    w.HTML('<div class="param-title">Outras Rendas (anuais)</div>'),
    w.HBox([r_tipo, r_val, r_ir]),
    w.HBox([r_cont, r_base]),
    r_obs,
    w.HBox([btn_add_r, btn_rm_r]),
    out_r
])
_render_r()

# --- Widgets: Redutor 16-B (alíquota PJ) ---
pj_cnpj = w.Dropdown(options=[], value=None, description="CNPJ", layout=w.Layout(width="400px"))

def _atualizar_cnpj_pj_options():
    """Atualiza as opções do dropdown de CNPJ baseado nos dividendos cadastrados"""
    if not df_divs.empty:
        cnpjs_unicos = df_divs['cnpj_pagador'].dropna().unique().tolist()
        if cnpjs_unicos:
            pj_cnpj.options = cnpjs_unicos
            if pj_cnpj.value is None:
                pj_cnpj.value = cnpjs_unicos[0]
        else:
            pj_cnpj.options = ["Nenhum CNPJ cadastrado"]
            pj_cnpj.value = "Nenhum CNPJ cadastrado"
    else:
        pj_cnpj.options = ["Nenhum CNPJ cadastrado"]
        pj_cnpj.value = "Nenhum CNPJ cadastrado"
pj_aliq = w.BoundedFloatText(description="Alíquota PJ (%)", value=34.0, min=0, max=60, step=0.5, layout=w.Layout(width="380px"))
pj_teto = w.Dropdown(options=list(TETOS_SETORIAIS.keys()), value="Geral (34%)", description="Teto setorial", layout=w.Layout(width="400px"))
btn_add_pj = w.Button(description="Adicionar", button_style="success", icon="plus")
btn_rm_pj  = w.Button(description="Remover última", button_style="warning", icon="trash")
out_pj     = w.Output()

def _add_pj(_):
    global df_pj
    add = dict(cnpj=pj_cnpj.value.strip(), aliquota_pj=float(pj_aliq.value), teto_setorial=pj_teto.value)
    new_row = pd.DataFrame([add])
    if df_pj.empty:
        df_pj = new_row.copy()
    else:
        df_pj = pd.concat([df_pj, new_row], ignore_index=True)
    _render_pj()

def _rm_pj(_):
    global df_pj
    if not df_pj.empty: df_pj = df_pj.iloc[:-1].copy()
    _render_pj()

def _render_pj():
    with out_pj:
        out_pj.clear_output()
        if df_pj.empty:
            display(Markdown("_Sem PJs cadastradas para redutor 16-B (opcional)._"))
        else:
            display(Markdown("**PJs para redutor 16-B**"))
            display(df_pj)

btn_add_pj.on_click(_add_pj); btn_rm_pj.on_click(_rm_pj)
pj_box = w.VBox([
    w.HTML('<div class="param-title">Alíquota efetiva PJ (redutor 16-B)</div>'),
    w.HTML('<div class="hint">💡 A alíquota PJ é atualizada automaticamente baseada no regime selecionado na seção Dividendos. O CNPJ é preenchido automaticamente com base nos dividendos cadastrados.</div>'),
    w.HBox([pj_cnpj, pj_aliq]),
    w.HBox([pj_teto]),
    w.HBox([btn_add_pj, btn_rm_pj]),
    out_pj
])
_render_pj()

# Inicializa o dropdown de CNPJ PJ
_atualizar_cnpj_pj_options()

# --- Botões principais + área de saída ---
btn_run = w.Button(description="RODAR SIMULAÇÃO", button_style="primary",
                   layout=w.Layout(width="260px", height="46px"), icon="play")
btn_pdf = w.Button(description="EXPORTAR PDF", button_style="info",
                   layout=w.Layout(width="260px", height="46px"), icon="file-pdf")
out_main = w.Output()

# --- Estilos CSS ---
css_style = """
<style>
.param-title {
    background-color: #f3f4f6;
    padding: 8px 12px;
    margin: 10px 0 5px 0;
    border-left: 4px solid #3b82f6;
    font-weight: bold;
    font-size: 14px;
}
.hint {
    color: #6b7280;
    font-size: 12px;
    font-style: italic;
    margin: 5px 0;
}
/* Estilos para widgets do ipywidgets */
.widget-label {
    white-space: nowrap !important;
    overflow: visible !important;
    text-overflow: unset !important;
    min-width: max-content !important;
}
.widget-text input, .widget-dropdown select {
    min-width: 200px !important;
}
/* Garante que os labels não sejam cortados */
.jp-InputPrompt, .jp-OutputPrompt {
    display: none !important;
}
</style>
"""

# --- Root da UI (todos os widgets visíveis) ---
root = w.VBox([
    w.HTML(css_style),
    w.HTML(f"<h2>{APP_TITLE}</h2><p>{APP_SUB}</p>"),
    param_box,
    w.HTML('<div style="margin: 20px 0;"></div>'),  # Espaçamento
    saldo_box,
    w.HTML('<div style="margin: 20px 0;"></div>'),  # Espaçamento
    div_box,
    w.HTML('<div style="margin: 20px 0;"></div>'),  # Espaçamento
    r_box,
    w.HTML('<div style="margin: 20px 0;"></div>'),  # Espaçamento
    pj_box,
    w.HTML('<div style="margin: 30px 0;"></div>'),  # Espaçamento maior antes dos botões
    w.HBox([btn_run, btn_pdf]),
    w.HTML('<div style="margin: 20px 0;"></div>'),  # Espaçamento
    out_main
])
display(root)

# =======================
# Lógica do Saldo Isento 2025
# =======================

def calcular_saldo_isento_2025():
    """Calcula o saldo isento 2025 baseado nas respostas do usuário"""
    # Q1: existe lucro não distribuído apurado até 2025?
    tem_lucro_nd = saldo_tem_lucro_nd.value

    # Q2: a deliberação foi aprovada até 31/12/2025?
    deliberado_2025 = saldo_deliberado_2025.value

    # Se ambas as respostas são "Sim", cria o saldo isento
    if tem_lucro_nd and deliberado_2025:
        saldo_aprovado = parse_brl(saldo_valor_aprovado.value)
        return saldo_aprovado
    else:
        return 0.0

def aplicar_regra_saldo_isento(df_dividendos, saldo_inicial, piso_mensal, irrf_frac):
    """
    Aplica a regra do saldo isento 2025 aos dividendos

    Args:
        df_dividendos: DataFrame com os dividendos
        saldo_inicial: Saldo isento disponível
        piso_mensal: Piso mensal para IRRF 10%
        irrf_frac: Fração do IRRF (ex: 0.10)

    Returns:
        DataFrame atualizado com valor_isento, valor_tributavel e irrf_10
    """
    df_result = df_dividendos.copy()
    saldo_disponivel = saldo_inicial

    # Data limite para uso do saldo isento
    data_limite = dt.date(2028, 12, 31)

    for idx, row in df_result.iterrows():
        data_pagamento = row['data']
        valor_total = row['valor']

        # Inicializa valores
        valor_isento = 0.0
        valor_tributavel = valor_total
        irrf_10 = 0.0

        # Verifica se a data está dentro do período de validade do saldo
        if data_pagamento <= data_limite and saldo_disponivel > 0:
            # Consome do saldo isento primeiro
            valor_isento = min(valor_total, saldo_disponivel)
            valor_tributavel = valor_total - valor_isento
            saldo_disponivel -= valor_isento

        # Aplica IRRF 10% apenas na parte tributável
        if valor_tributavel > 0:
            # Aqui seria necessário verificar se passa do piso mensal por CNPJ
            # Por simplicidade, vamos assumir que aplica sempre
            irrf_10 = valor_tributavel * irrf_frac

        # Atualiza o DataFrame
        df_result.loc[idx, 'valor_isento'] = valor_isento
        df_result.loc[idx, 'valor_tributavel'] = valor_tributavel
        df_result.loc[idx, 'irrf_10'] = irrf_10

    return df_result, saldo_disponivel

# =======================
# Cálculo
# =======================
def expand_dividends_rows(df):
    if df.empty:
        return pd.DataFrame(columns=["ano","mes","ym","cnpj_pagador","valor","residente","regime_pj","irrf_10"])
    rows=[]
    for _,r in df.iterrows():
        n = int(r["n_meses"] or 1)
        base_date = pd.to_datetime(r["data"]) if pd.notnull(r["data"]) else pd.Timestamp("2026-01-01")
        if r["periodicidade"].startswith("Única"):
            pagos = [(base_date, float(r["valor"]))]
        else:
            step = 1 if r["periodicidade"].startswith("Mensal") else 3
            val_mes = (float(r["valor"])/n) if n>0 else float(r["valor"])
            pagos=[]; d=base_date
            for _ in range(n):
                pagos.append((d, val_mes))
                m = d.month + step; y = d.year + (m-1)//12; m = ((m-1)%12)+1
                d = dt.date(y, m, min(d.day, 28))
        for dte, v in pagos:
            ym = f"{dte.year}-{dte.month:02d}"
            rows.append(dict(ano=dte.year, mes=dte.month, ym=ym,
                             cnpj_pagador=r["cnpj_pagador"], valor=float(v),
                             residente=int(r["beneficiario_residente_brasil"]),
                             regime_pj=r["regime_pj"], irrf_10=0.0))
    out = pd.DataFrame(rows)
    if len(out):
        out = out.groupby(["ano","mes","ym","cnpj_pagador","residente","regime_pj"], as_index=False)["valor"].sum()
        out["irrf_10"] = 0.0
    return out

def aliquota_irpfm(REND, piso0, topo10):
    REND = max(0.0, float(REND)); piso0=float(piso0); topo10=float(topo10)
    if REND <= piso0: return 0.0
    if REND >= topo10: return 0.10
    return 0.10 * ((REND - piso0)/(topo10 - piso0))

def exportar_pdf(_=None):
    """Exporta relatório em PDF usando weasyprint"""
    try:
        from weasyprint import HTML, CSS
        from datetime import datetime
        import os

        # Coleta dados atuais
        piso_m = parse_brl(p_piso.value)
        irrf_frac = float(p_irrf_f.value)
        piso0 = parse_brl(p_r0.value)
        topo10 = parse_brl(p_r10.value)

        # Calcula totais básicos
        total_div = float(df_divs["valor"].sum()) if not df_divs.empty else 0.0
        rend_r = float(df_rends.loc[df_rends["conta_para_REND"]==1, "valor_anual"].sum()) if not df_rends.empty else 0.0
        base_r = float(df_rends.loc[df_rends["inclui_na_base"]==1, "valor_anual"].sum()) if not df_rends.empty else 0.0
        REND_total = total_div + rend_r
        BASE_total = total_div + base_r

        # Gera nome do arquivo
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"relatorio_irrf_irpfm_{timestamp}.pdf"

        # HTML para PDF
        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Relatório Simulador IRRF/IRPFM</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        .header {{ text-align: center; margin-bottom: 30px; }}
        .section {{ margin: 20px 0; }}
        .highlight {{ background-color: #f0f8ff; padding: 15px; border-left: 5px solid #3b82f6; }}
        .company-box {{ background-color: #fee2e2; border: 2px solid #dc2626; padding: 15px; margin: 10px 0; }}
        .person-box {{ background-color: #dbeafe; border: 2px solid #2563eb; padding: 15px; margin: 10px 0; }}
        table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f2f2f2; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>Simulador IRRF 10% + IRPFM 0–10% — PL 1.087/2025</h1>
        <p>Relatório gerado em: {datetime.now().strftime('%d/%m/%Y às %H:%M')}</p>
    </div>

    <div class="section">
        <h2>📋 Parâmetros Utilizados</h2>
        <ul>
            <li><strong>Piso mensal PF:</strong> {fmt_brl(piso_m)}</li>
            <li><strong>IRRF Div. (fração):</strong> {irrf_frac:.2%}</li>
            <li><strong>REND 0% até:</strong> {fmt_brl(piso0)}</li>
            <li><strong>REND 10% a partir:</strong> {fmt_brl(topo10)}</li>
        </ul>
    </div>

    <div class="section">
        <h2>💰 Resumo dos Impostos</h2>
        <div class="company-box">
            <h3>🏢 EMPRESA PAGA</h3>
            <p style="font-size: 24px; font-weight: bold; color: #dc2626;">
                {fmt_brl(IRRF10_ano_global)}
            </p>
            <p>IRRF 10% sobre dividendos (quando > R$ 50.000/mês)</p>
        </div>

        <div class="person-box">
            <h3>👤 PESSOA FÍSICA PAGA</h3>
            <p style="font-size: 24px; font-weight: bold; color: #2563eb;">
                {fmt_brl(IRPFM_final_global)}
            </p>
            <p>IRPFM no ajuste anual (0-10% sobre REND)</p>
        </div>
    </div>

    <div class="section">
        <h2>📊 Base de Cálculo</h2>
        <div class="highlight">
            <p><strong>REND Total (§1):</strong> {fmt_brl(REND_total)}</p>
            <p><strong>BASE Total (§3):</strong> {fmt_brl(BASE_total)}</p>
        </div>
    </div>

    <div class="section">
        <h2>📈 Dividendos Cadastrados</h2>
        <table>
            <tr>
                <th>Data</th>
                <th>CNPJ</th>
                <th>Valor</th>
                <th>Periodicidade</th>
                <th>Meses</th>
            </tr>"""

        # Adiciona dados dos dividendos
        if not df_divs.empty:
            for _, row in df_divs.iterrows():
                html_content += f"""
            <tr>
                <td>{row['data']}</td>
                <td>{row['cnpj_pagador']}</td>
                <td>{fmt_brl(row['valor'])}</td>
                <td>{row['periodicidade']}</td>
                <td>{row['n_meses']}</td>
            </tr>"""
        else:
            html_content += "<tr><td colspan='5'>Nenhum dividendo cadastrado</td></tr>"

        html_content += """
        </table>
    </div>

    <div class="section">
        <h2>💼 Outras Rendas Cadastradas</h2>
        <table>
            <tr>
                <th>Tipo</th>
                <th>Valor Anual</th>
                <th>Conta REND</th>
                <th>Inclui Base</th>
            </tr>"""

        # Adiciona dados das outras rendas
        if not df_rends.empty:
            for _, row in df_rends.iterrows():
                html_content += f"""
            <tr>
                <td>{row['tipo']}</td>
                <td>{fmt_brl(row['valor_anual'])}</td>
                <td>{'Sim' if row['conta_para_REND'] else 'Não'}</td>
                <td>{'Sim' if row['inclui_na_base'] else 'Não'}</td>
            </tr>"""
        else:
            html_content += "<tr><td colspan='4'>Nenhuma outra renda cadastrada</td></tr>"

        html_content += """
        </table>
    </div>

    <div class="section">
        <p style="font-size: 12px; color: #666; text-align: center;">
            Este relatório foi gerado pelo Simulador IRRF/IRPFM - PL 1.087/2025<br>
            Simulação educacional; pontos como o redutor 16-B são aproximados.
        </p>
    </div>
</body>
</html>"""

        # Gera PDF
        html_doc = HTML(string=html_content)
        css = CSS(string='@page { size: A4; margin: 1cm; }')

        # Salva arquivo
        html_doc.write_pdf(filename, stylesheets=[css])

        # Verifica se o arquivo foi criado
        if os.path.exists(filename):
            # Exibe mensagem de sucesso
            with out_main:
                out_main.clear_output()
                display(HTML(f"""
                    <div style="background:#d1fae5;border:2px solid #10b981;border-radius:8px;padding:15px;margin:10px 0;">
                        <h3 style="margin:0;color:#065f46;">✅ Relatório exportado com sucesso!</h3>
                        <p style="margin:5px 0;color:#065f46;"><strong>Arquivo:</strong> {filename}</p>
                        <p style="margin:5px 0;color:#065f46;">O arquivo PDF foi salvo no diretório atual.</p>
                    </div>
                """))
        else:
            raise Exception("Arquivo PDF não foi criado")

    except ImportError:
        with out_main:
            out_main.clear_output()
            display(HTML("""
                <div style="background:#fef3c7;border:2px solid #f59e0b;border-radius:8px;padding:15px;margin:10px 0;">
                    <h3 style="margin:0;color:#92400e;">⚠️ Biblioteca não encontrada</h3>
                    <p style="margin:5px 0;color:#92400e;">Para exportar PDF, instale: <code>pip install weasyprint</code></p>
                </div>
            """))
    except Exception as e:
        with out_main:
            out_main.clear_output()
            display(HTML(f"""
                <div style="background:#fee2e2;border:2px solid #ef4444;border-radius:8px;padding:15px;margin:10px 0;">
                    <h3 style="margin:0;color:#991b1b;">❌ Erro na exportação</h3>
                    <p style="margin:5px 0;color:#991b1b;">{str(e)}</p>
                </div>
            """))

def calcular(_=None):
    try:
        piso_m = parse_brl(p_piso.value)
        irrf_frac = float(p_irrf_f.value)
        piso0 = parse_brl(p_r0.value); topo10=parse_brl(p_r10.value)
        usar_16b = bool(p_use16b.value)

        # Calcula saldo isento 2025
        saldo_isento_2025 = calcular_saldo_isento_2025()

        # Aplica a regra do saldo isento aos dividendos
        df_divs_atualizado, saldo_restante = aplicar_regra_saldo_isento(df_divs, saldo_isento_2025, piso_m, irrf_frac)

        mov = expand_dividends_rows(df_divs_atualizado)
        # IRRF 10% por mês/CNPJ
        if len(mov):
            for (ym, cnpj), sub in mov.groupby(["ym","cnpj_pagador"]):
                tot = sub["valor"].sum()
                if tot > piso_m:
                    idx = (mov["ym"]==ym)&(mov["cnpj_pagador"]==cnpj)
                    mov.loc[idx, "irrf_10"] = mov.loc[idx, "valor"] * irrf_frac

        # REND e BASE
        total_div = float(df_divs_atualizado["valor"].sum()) if not df_divs_atualizado.empty else 0.0
        rend_r = float(df_rends.loc[df_rends["conta_para_REND"]==1, "valor_anual"].sum()) if not df_rends.empty else 0.0
        base_r = float(df_rends.loc[df_rends["inclui_na_base"]==1, "valor_anual"].sum()) if not df_rends.empty else 0.0
        IR_excl = float(df_rends["irrf_exclusivo_fonte"].sum()) if not df_rends.empty else 0.0

        # Valores específicos do saldo isento
        total_div_isento = float(df_divs_atualizado["valor_isento"].sum()) if not df_divs_atualizado.empty else 0.0
        total_div_tributavel = float(df_divs_atualizado["valor_tributavel"].sum()) if not df_divs_atualizado.empty else 0.0

        REND_total = total_div + rend_r
        BASE_total = total_div + base_r

        a_irpfm = aliquota_irpfm(REND_total, piso0, topo10)
        IRPFM_bruto = BASE_total * a_irpfm

        # IRRF10_ano agora vem da aplicação da regra do saldo isento
        IRRF10_ano = float(df_divs_atualizado["irrf_10"].sum()) if not df_divs_atualizado.empty else 0.0

        IRPFM_pos = max(0.0, IRPFM_bruto - IR_excl - IRRF10_ano)

        # Redutor 16-B (aprox)
        red16 = 0.0
        if usar_16b and IRPFM_pos>0 and BASE_total>0 and total_div>0:
            prop_div = total_div/BASE_total
            IRPFM_div = IRPFM_pos * prop_div
            aliq_div_pct = (IRPFM_div/total_div)*100.0 if total_div>0 else 0.0
            aliq_pj = 34.0; teto_pct = 34.0
            if not df_pj.empty:
                aliq_pj = float(df_pj["aliquota_pj"].max())
                teto_pct = float(min([TETOS_SETORIAIS.get(t,34.0) for t in df_pj["teto_setorial"].tolist()])) or 34.0
            soma = aliq_pj + aliq_div_pct
            if soma > teto_pct:
                excesso = soma - teto_pct
                red16 = (excesso/100.0) * total_div

        IRPFM_final = max(0.0, IRPFM_pos - red16)

        # --- NOVA LÓGICA DE CONCILIAÇÃO (Art. 13) ---
        # A) IRPF Normal Anual
        ir_devido_anual, irrf_normal, saldo_irpf_normal = apurar_irpf_normal_anual(df_rends, deducoes=0)

        # B) IRPFM Detalhado
        irpfm_bruto, irpfm_liquido, irpfm_antecipado, saldo_irpfm, aliq_irpfm, base_irpfm, rend_total = apurar_irpfm(
            df_rends, df_divs_atualizado, df_pj, ir_devido_anual, deducoes_extras=0
        )

        # C) Conciliação Final (Art. 13)
        tipo_resultado, valor_restituicao, valor_a_pagar = conciliar_final_art13(saldo_irpf_normal, saldo_irpfm)

        # Salva variáveis globais para exportação PDF
        global IRRF10_ano_global, IRPFM_final_global, saldo_isento_2025_global, saldo_restante_global
        global restituicao_global, a_pagar_global, tipo_resultado_global
        global ir_devido_anual_global, irrf_normal_global, saldo_irpf_normal_global

        IRRF10_ano_global = IRRF10_ano
        IRPFM_final_global = IRPFM_final
        saldo_isento_2025_global = saldo_isento_2025
        saldo_restante_global = saldo_restante
        restituicao_global = valor_restituicao
        a_pagar_global = valor_a_pagar
        tipo_resultado_global = tipo_resultado
        ir_devido_anual_global = ir_devido_anual
        irrf_normal_global = irrf_normal
        saldo_irpf_normal_global = saldo_irpf_normal

        # --- Saída HTML melhorada ---
        out_main.clear_output()
        with out_main:
            # Resumo principal com destaque para empresa vs PF
            html = f"""
        <div style="border:2px solid #3b82f6;border-radius:12px;padding:20px;margin:15px 0;background:linear-gradient(135deg,#f8fafc,#e2e8f0);">
          <h2 style="margin:0 0 15px 0;color:#1e40af;text-align:center;">💰 RESUMO DOS IMPOSTOS</h2>

          <div style="display:flex;justify-content:space-between;gap:20px;margin:15px 0;">
            <div style="flex:1;background:#fee2e2;border:2px solid #dc2626;border-radius:8px;padding:15px;text-align:center;">
              <h3 style="margin:0 0 8px 0;color:#dc2626;">🏢 EMPRESA PAGA</h3>
              <div style="font-size:24px;font-weight:bold;color:#dc2626;">{fmt_brl(IRRF10_ano)}</div>
              <div style="font-size:12px;color:#7f1d1d;">IRRF 10% sobre dividendos<br/>(quando > R$ 50.000/mês)</div>
            </div>

            <div style="flex:1;background:#dbeafe;border:2px solid #2563eb;border-radius:8px;padding:15px;text-align:center;">
              <h3 style="margin:0 0 8px 0;color:#2563eb;">👤 PESSOA FÍSICA PAGA</h3>
              <div style="font-size:24px;font-weight:bold;color:#2563eb;">{fmt_brl(IRPFM_final)}</div>
              <div style="font-size:12px;color:#1e3a8a;">IRPFM no ajuste anual<br/>(0-10% sobre REND)</div>
            </div>
          </div>"""

        # Adiciona seção de Conciliação Final (Art. 13)
        if tipo_resultado == "restituir":
            html += f"""
          <div style="background:#d1fae5;border:3px solid #10b981;border-radius:10px;padding:20px;margin:20px 0;text-align:center;">
            <h2 style="margin:0 0 10px 0;color:#065f46;">✅ VOCÊ VAI RECEBER DE VOLTA!</h2>
            <div style="font-size:32px;font-weight:bold;color:#047857;margin:10px 0;">{fmt_brl(valor_restituicao)}</div>
            <div style="font-size:14px;color:#065f46;margin-top:10px;">
              💡 <strong>Restituição</strong> — O valor pago a maior será devolvido pela Receita Federal.<br/>
              Base legal: Art. 13 (conciliação IRPF + IRPFM)
            </div>
          </div>"""
        elif tipo_resultado == "pagar" and valor_a_pagar > 0:
            html += f"""
          <div style="background:#fee2e2;border:3px solid #dc2626;border-radius:10px;padding:20px;margin:20px 0;text-align:center;">
            <h2 style="margin:0 0 10px 0;color:#7f1d1d;">⚠️ IMPOSTO A PAGAR</h2>
            <div style="font-size:32px;font-weight:bold;color:#b91c1c;margin:10px 0;">{fmt_brl(valor_a_pagar)}</div>
            <div style="font-size:14px;color:#7f1d1d;margin-top:10px;">
              💡 Saldo devedor no ajuste anual — pagar em DARF até o prazo legal.<br/>
              Base legal: Art. 13 (conciliação IRPF + IRPFM)
            </div>
          </div>"""
        else:
            html += f"""
          <div style="background:#d1fae5;border:3px solid #10b981;border-radius:10px;padding:20px;margin:20px 0;text-align:center;">
            <h2 style="margin:0 0 10px 0;color:#065f46;">✅ VOCÊ NÃO PRECISA PAGAR NADA!</h2>
            <div style="font-size:24px;font-weight:bold;color:#047857;margin:10px 0;">R$ 0,00</div>
            <div style="font-size:14px;color:#065f46;margin-top:10px;">
              💡 Seus impostos já foram pagos corretamente durante o ano.<br/>
              Base legal: Art. 13 (conciliação IRPF + IRPFM)
            </div>
          </div>"""

        html += f"""

          <div style="background:white;border:1px solid #d1d5db;border-radius:8px;padding:12px;margin-top:15px;">
            <div style="font-size:14px;color:#374151;text-align:center;">
              <b>📊 BASE DE CÁLCULO:</b> REND {fmt_brl(REND_total)} • BASE {fmt_brl(BASE_total)} • Alíquota IRPFM {a_irpfm*100:.2f}%
            </div>
          </div>

          {f'''<div style="background:#f0f9ff;border:2px solid #0ea5e9;border-radius:8px;padding:15px;margin-top:15px;">
            <h3 style="margin:0 0 10px 0;color:#0c4a6e;font-size:16px;">💎 SALDO ISENTO 2025</h3>
            <div style="display:flex;justify-content:space-between;gap:15px;font-size:14px;">
              <div><b>Saldo inicial:</b> {fmt_brl(saldo_isento_2025)}</div>
              <div><b>Saldo utilizado:</b> {fmt_brl(saldo_isento_2025 - saldo_restante)}</div>
              <div><b>Saldo restante:</b> {fmt_brl(saldo_restante)}</div>
            </div>
            <div style="font-size:12px;color:#0c4a6e;margin-top:8px;">
              Dividendos isentos: {fmt_brl(total_div_isento)} | Dividendos tributáveis: {fmt_brl(total_div_tributavel)}
            </div>
          </div>''' if saldo_isento_2025 > 0 else ''}
        </div>
        """
        display(HTML(html))

        # Explicações
        expl = []
        if len(mov) and IRRF10_ano>0:
            expl.append(f"Houve IRRF 10% em mês(es) com total por CNPJ > {fmt_brl(piso_m)}.")
        else:
            expl.append(f"Não houve IRRF 10%: nenhum mês passou de {fmt_brl(piso_m)} por CNPJ.")

        if a_irpfm>0:
            expl.append(f"REND anual {fmt_brl(REND_total)} acima de {fmt_brl(piso0)} ⇒ alíquota {a_irpfm*100:.2f}%; BASE {fmt_brl(BASE_total)}.")
        else:
            expl.append(f"REND anual {fmt_brl(REND_total)} no piso (≤ {fmt_brl(piso0)}), alíquota 0%.")

        if IR_excl>0: expl.append(f"Abatido IR exclusivo/definitivo em rendas: {fmt_brl(IR_excl)}.")
        if IRRF10_ano>0: expl.append(f"Abatido IRRF 10% de dividendos: {fmt_brl(IRRF10_ano)}.")
        if red16>0: expl.append(f"Aplicado redutor 16-B de {fmt_brl(red16)} (teto setorial).")
        else:       expl.append("Redutor 16-B não aplicável.")

        display(Markdown("#### Entenda o resultado"))
        for e in expl: display(Markdown(f"- {e}"))

        # IRRF 10% mês/CNPJ
        display(Markdown("#### IRRF 10% por mês/CNPJ (após transição)"))
        if len(mov):
            sh = mov[["ano","mes","ym","cnpj_pagador","valor","irrf_10"]].copy().sort_values(["ano","mes","cnpj_pagador"])
            sh["valor"] = sh["valor"].map(fmt_brl); sh["irrf_10"] = sh["irrf_10"].map(fmt_brl)
            display(sh.reset_index(drop=True))
        else:
            display(Markdown("_Sem lançamentos de dividendos._"))

        # Resumo anual
        display(Markdown("#### Resumo do IRPFM anual"))
        df_sum = pd.DataFrame([{
            "REND_total_(§1)": REND_total, "BASE_(§3)": BASE_total,
            "aliquota_IRPFM_%": f"{a_irpfm*100:.2f}%",
            "IRPFM_bruto": IRPFM_bruto,
            "IR_exclusivo_em_rendas": IR_excl,
            "IRRF10_dividendos": IRRF10_ano,
            "IRPFM_pos_deducoes": IRPFM_pos,
            "redutor_16B_(aprox)": red16,
            "IRPFM_final_a_pagar": IRPFM_final
        }])
        for c in ["REND_total_(§1)","BASE_(§3)","IRPFM_bruto","IR_exclusivo_em_rendas","IRRF10_dividendos",
                  "IRPFM_pos_deducoes","redutor_16B_(aprox)","IRPFM_final_a_pagar"]:
            df_sum[c] = df_sum[c].map(fmt_brl)
        display(df_sum)

    except Exception as e:
        log_error("Erro durante o cálculo da simulação", e)

# Variáveis globais para exportação PDF
IRRF10_ano_global = 0.0
IRPFM_final_global = 0.0
saldo_isento_2025_global = 0.0
saldo_restante_global = 0.0
restituicao_global = 0.0
a_pagar_global = 0.0
tipo_resultado_global = ""
ir_devido_anual_global = 0.0
irrf_normal_global = 0.0
saldo_irpf_normal_global = 0.0

btn_run.on_click(calcular)
btn_pdf.on_click(exportar_pdf)

# Mensagem inicial
with out_main:
    out_main.clear_output()
    display(Markdown("_Preencha os campos e clique em **RODAR SIMULAÇÃO**._"))